services:
  mysql:
    image: mysql:latest
    container_name: tce_sp_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  scraping:
    restart: unless-stopped
    build: .
    env_file:
        - ./.env    
    command: python main.py
    depends_on: 
      - mysql
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.13.4
    ports:
      - "9200:9200"
      - "9300:9300"
      
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
