services:
  mysql:
    image: mysql:latest
    container_name: teste_turivius
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  scraping:
    restart: unless-stopped
    build: .
    env_file:
        - ./.env    
    command: python main.py
    depends_on: 
      - mysql
